// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_import, invalid_annotation_target, unnecessary_import

import 'package:json_annotation/json_annotation.dart';

/// Error codes returned by API operations
@JsonEnum()
enum ApiErrorCode {
  @JsonValue('ACCESS_DENIED')
  accessDenied('ACCESS_DENIED'),
  @JsonValue('BAD_GATEWAY')
  badGateway('BAD_GATEWAY'),
  @JsonValue('BAD_REQUEST')
  badRequest('BAD_REQUEST'),
  @JsonValue('BLUESKY_OAUTH_AUTHORIZATION_FAILED')
  blueskyOauthAuthorizationFailed('BLUESKY_OAUTH_AUTHORIZATION_FAILED'),
  @JsonValue('BLUESKY_OAUTH_CALLBACK_FAILED')
  blueskyOauthCallbackFailed('BLUESKY_OAUTH_CALLBACK_FAILED'),
  @JsonValue('BLUESKY_OAUTH_NOT_ENABLED')
  blueskyOauthNotEnabled('BLUESKY_OAUTH_NOT_ENABLED'),
  @JsonValue('BLUESKY_OAUTH_STATE_INVALID')
  blueskyOauthStateInvalid('BLUESKY_OAUTH_STATE_INVALID'),
  @JsonValue('ACCOUNT_SUSPENDED_PERMANENTLY')
  accountSuspendedPermanently('ACCOUNT_SUSPENDED_PERMANENTLY'),
  @JsonValue('ACCOUNT_SUSPENDED_TEMPORARILY')
  accountSuspendedTemporarily('ACCOUNT_SUSPENDED_TEMPORARILY'),
  @JsonValue('ACCOUNT_SUSPICIOUS_ACTIVITY')
  accountSuspiciousActivity('ACCOUNT_SUSPICIOUS_ACTIVITY'),
  @JsonValue('ACCOUNT_TOO_NEW_FOR_GUILD')
  accountTooNewForGuild('ACCOUNT_TOO_NEW_FOR_GUILD'),
  @JsonValue('ACLS_MUST_BE_NON_EMPTY')
  aclsMustBeNonEmpty('ACLS_MUST_BE_NON_EMPTY'),
  @JsonValue('ADMIN_API_KEY_NOT_FOUND')
  adminApiKeyNotFound('ADMIN_API_KEY_NOT_FOUND'),
  @JsonValue('APPLICATION_NOT_OWNED')
  applicationNotOwned('APPLICATION_NOT_OWNED'),
  @JsonValue('ALREADY_FRIENDS')
  alreadyFriends('ALREADY_FRIENDS'),
  @JsonValue('BOTS_CANNOT_CREATE_GUILDS')
  botsCannotCreateGuilds('BOTS_CANNOT_CREATE_GUILDS'),
  @JsonValue('BOTS_CANNOT_SEND_FRIEND_REQUESTS')
  botsCannotSendFriendRequests('BOTS_CANNOT_SEND_FRIEND_REQUESTS'),
  @JsonValue('BOT_ALREADY_IN_GUILD')
  botAlreadyInGuild('BOT_ALREADY_IN_GUILD'),
  @JsonValue('BOT_IS_PRIVATE')
  botIsPrivate('BOT_IS_PRIVATE'),
  @JsonValue('BOT_USER_AUTH_ENDPOINT_ACCESS_DENIED')
  botUserAuthEndpointAccessDenied('BOT_USER_AUTH_ENDPOINT_ACCESS_DENIED'),
  @JsonValue('BOT_USER_AUTH_SESSION_CREATION_DENIED')
  botUserAuthSessionCreationDenied('BOT_USER_AUTH_SESSION_CREATION_DENIED'),
  @JsonValue('BOT_USER_GENERATION_FAILED')
  botUserGenerationFailed('BOT_USER_GENERATION_FAILED'),
  @JsonValue('BOT_USER_NOT_FOUND')
  botUserNotFound('BOT_USER_NOT_FOUND'),
  @JsonValue('CALL_ALREADY_EXISTS')
  callAlreadyExists('CALL_ALREADY_EXISTS'),
  @JsonValue('CANNOT_EDIT_OTHER_USER_MESSAGE')
  cannotEditOtherUserMessage('CANNOT_EDIT_OTHER_USER_MESSAGE'),
  @JsonValue('CANNOT_EXECUTE_ON_DM')
  cannotExecuteOnDm('CANNOT_EXECUTE_ON_DM'),
  @JsonValue('CANNOT_BLOCK_SYSTEM_USER')
  cannotBlockSystemUser('CANNOT_BLOCK_SYSTEM_USER'),
  @JsonValue('CANNOT_MODIFY_SYSTEM_WEBHOOK')
  cannotModifySystemWebhook('CANNOT_MODIFY_SYSTEM_WEBHOOK'),
  @JsonValue('CANNOT_REDEEM_PLUTONIUM_WITH_VISIONARY')
  cannotRedeemPlutoniumWithVisionary('CANNOT_REDEEM_PLUTONIUM_WITH_VISIONARY'),
  @JsonValue('CANNOT_REPORT_GUILD')
  cannotReportGuild('CANNOT_REPORT_GUILD'),
  @JsonValue('CANNOT_REPORT_OWN_GUILD')
  cannotReportOwnGuild('CANNOT_REPORT_OWN_GUILD'),
  @JsonValue('CANNOT_REPORT_OWN_MESSAGE')
  cannotReportOwnMessage('CANNOT_REPORT_OWN_MESSAGE'),
  @JsonValue('CANNOT_REPORT_YOURSELF')
  cannotReportYourself('CANNOT_REPORT_YOURSELF'),
  @JsonValue('CANNOT_SEND_EMPTY_MESSAGE')
  cannotSendEmptyMessage('CANNOT_SEND_EMPTY_MESSAGE'),
  @JsonValue('CANNOT_SEND_FRIEND_REQUEST_TO_BLOCKED_USER')
  cannotSendFriendRequestToBlockedUser(
    'CANNOT_SEND_FRIEND_REQUEST_TO_BLOCKED_USER',
  ),
  @JsonValue('CANNOT_SEND_FRIEND_REQUEST_TO_SELF')
  cannotSendFriendRequestToSelf('CANNOT_SEND_FRIEND_REQUEST_TO_SELF'),
  @JsonValue('CANNOT_SEND_MESSAGES_IN_NON_TEXT_CHANNEL')
  cannotSendMessagesInNonTextChannel(
    'CANNOT_SEND_MESSAGES_IN_NON_TEXT_CHANNEL',
  ),
  @JsonValue('CANNOT_SEND_MESSAGES_TO_USER')
  cannotSendMessagesToUser('CANNOT_SEND_MESSAGES_TO_USER'),
  @JsonValue('CANNOT_TRANSFER_OWNERSHIP_TO_BOT')
  cannotTransferOwnershipToBot('CANNOT_TRANSFER_OWNERSHIP_TO_BOT'),
  @JsonValue('CANNOT_SHRINK_RESERVED_SLOTS')
  cannotShrinkReservedSlots('CANNOT_SHRINK_RESERVED_SLOTS'),
  @JsonValue('CAPTCHA_REQUIRED')
  captchaRequired('CAPTCHA_REQUIRED'),
  @JsonValue('COMMUNICATION_DISABLED')
  communicationDisabled('COMMUNICATION_DISABLED'),
  @JsonValue('CONNECTION_ALREADY_EXISTS')
  connectionAlreadyExists('CONNECTION_ALREADY_EXISTS'),
  @JsonValue('CONNECTION_INITIATION_TOKEN_INVALID')
  connectionInitiationTokenInvalid('CONNECTION_INITIATION_TOKEN_INVALID'),
  @JsonValue('CONNECTION_INVALID_TYPE')
  connectionInvalidType('CONNECTION_INVALID_TYPE'),
  @JsonValue('CONNECTION_LIMIT_REACHED')
  connectionLimitReached('CONNECTION_LIMIT_REACHED'),
  @JsonValue('CONNECTION_NOT_FOUND')
  connectionNotFound('CONNECTION_NOT_FOUND'),
  @JsonValue('CONNECTION_VERIFICATION_FAILED')
  connectionVerificationFailed('CONNECTION_VERIFICATION_FAILED'),
  @JsonValue('CONFLICT')
  conflict('CONFLICT'),
  @JsonValue('CONTENT_BLOCKED')
  contentBlocked('CONTENT_BLOCKED'),
  @JsonValue('DELETION_FAILED')
  deletionFailed('DELETION_FAILED'),
  @JsonValue('DISCOVERY_ALREADY_APPLIED')
  discoveryAlreadyApplied('DISCOVERY_ALREADY_APPLIED'),
  @JsonValue('DISCOVERY_APPLICATION_ALREADY_REVIEWED')
  discoveryApplicationAlreadyReviewed('DISCOVERY_APPLICATION_ALREADY_REVIEWED'),
  @JsonValue('DISCOVERY_APPLICATION_NOT_FOUND')
  discoveryApplicationNotFound('DISCOVERY_APPLICATION_NOT_FOUND'),
  @JsonValue('DISCOVERY_DISABLED')
  discoveryDisabled('DISCOVERY_DISABLED'),
  @JsonValue('DISCOVERY_INSUFFICIENT_MEMBERS')
  discoveryInsufficientMembers('DISCOVERY_INSUFFICIENT_MEMBERS'),
  @JsonValue('DISCOVERY_NOT_DISCOVERABLE')
  discoveryNotDiscoverable('DISCOVERY_NOT_DISCOVERABLE'),
  @JsonValue('DISCRIMINATOR_REQUIRED')
  discriminatorRequired('DISCRIMINATOR_REQUIRED'),
  @JsonValue('EMAIL_SERVICE_NOT_TESTABLE')
  emailServiceNotTestable('EMAIL_SERVICE_NOT_TESTABLE'),
  @JsonValue('EMAIL_VERIFICATION_REQUIRED')
  emailVerificationRequired('EMAIL_VERIFICATION_REQUIRED'),
  @JsonValue('DIRECT_MESSAGE_EMAIL_VERIFICATION_REQUIRED')
  directMessageEmailVerificationRequired(
    'DIRECT_MESSAGE_EMAIL_VERIFICATION_REQUIRED',
  ),
  @JsonValue('FRIEND_REQUEST_EMAIL_VERIFICATION_REQUIRED')
  friendRequestEmailVerificationRequired(
    'FRIEND_REQUEST_EMAIL_VERIFICATION_REQUIRED',
  ),
  @JsonValue('GUILD_CREATION_EMAIL_VERIFICATION_REQUIRED')
  guildCreationEmailVerificationRequired(
    'GUILD_CREATION_EMAIL_VERIFICATION_REQUIRED',
  ),
  @JsonValue('GUILD_EMAIL_VERIFICATION_REQUIRED')
  guildEmailVerificationRequired('GUILD_EMAIL_VERIFICATION_REQUIRED'),
  @JsonValue('MFA_EMAIL_VERIFICATION_REQUIRED')
  mfaEmailVerificationRequired('MFA_EMAIL_VERIFICATION_REQUIRED'),
  @JsonValue('PROFILE_EMAIL_VERIFICATION_REQUIRED')
  profileEmailVerificationRequired('PROFILE_EMAIL_VERIFICATION_REQUIRED'),
  @JsonValue('PURCHASE_EMAIL_VERIFICATION_REQUIRED')
  purchaseEmailVerificationRequired('PURCHASE_EMAIL_VERIFICATION_REQUIRED'),
  @JsonValue('REACTION_EMAIL_VERIFICATION_REQUIRED')
  reactionEmailVerificationRequired('REACTION_EMAIL_VERIFICATION_REQUIRED'),
  @JsonValue('REPORT_EMAIL_VERIFICATION_REQUIRED')
  reportEmailVerificationRequired('REPORT_EMAIL_VERIFICATION_REQUIRED'),
  @JsonValue('REGISTRATION_CLOSED')
  registrationClosed('REGISTRATION_CLOSED'),
  @JsonValue('REGISTRATION_PENDING_APPROVAL')
  registrationPendingApproval('REGISTRATION_PENDING_APPROVAL'),
  @JsonValue('REGISTRATION_REJECTED')
  registrationRejected('REGISTRATION_REJECTED'),
  @JsonValue('REGISTRATION_URL_INVALID')
  registrationUrlInvalid('REGISTRATION_URL_INVALID'),
  @JsonValue('EXPLICIT_CONTENT_CANNOT_BE_SENT')
  explicitContentCannotBeSent('EXPLICIT_CONTENT_CANNOT_BE_SENT'),
  @JsonValue('FEATURE_NOT_AVAILABLE_SELF_HOSTED')
  featureNotAvailableSelfHosted('FEATURE_NOT_AVAILABLE_SELF_HOSTED'),
  @JsonValue('FEATURE_TEMPORARILY_DISABLED')
  featureTemporarilyDisabled('FEATURE_TEMPORARILY_DISABLED'),
  @JsonValue('FILE_SIZE_TOO_LARGE')
  fileSizeTooLarge('FILE_SIZE_TOO_LARGE'),
  @JsonValue('FORBIDDEN')
  forbidden('FORBIDDEN'),
  @JsonValue('FRIEND_REQUEST_BLOCKED')
  friendRequestBlocked('FRIEND_REQUEST_BLOCKED'),
  @JsonValue('GATEWAY_TIMEOUT')
  gatewayTimeout('GATEWAY_TIMEOUT'),
  @JsonValue('GENERAL_ERROR')
  generalError('GENERAL_ERROR'),
  @JsonValue('GONE')
  gone('GONE'),
  @JsonValue('GIFT_CODE_ALREADY_REDEEMED')
  giftCodeAlreadyRedeemed('GIFT_CODE_ALREADY_REDEEMED'),
  @JsonValue('GUILD_PHONE_VERIFICATION_REQUIRED')
  guildPhoneVerificationRequired('GUILD_PHONE_VERIFICATION_REQUIRED'),
  @JsonValue('GUILD_TEMPLATE_INVALID')
  guildTemplateInvalid('GUILD_TEMPLATE_INVALID'),
  @JsonValue('GUILD_VERIFICATION_REQUIRED')
  guildVerificationRequired('GUILD_VERIFICATION_REQUIRED'),
  @JsonValue('HANDOFF_CODE_EXPIRED')
  handoffCodeExpired('HANDOFF_CODE_EXPIRED'),
  @JsonValue('HARVEST_EXPIRED')
  harvestExpired('HARVEST_EXPIRED'),
  @JsonValue('HARVEST_FAILED')
  harvestFailed('HARVEST_FAILED'),
  @JsonValue('HARVEST_NOT_READY')
  harvestNotReady('HARVEST_NOT_READY'),
  @JsonValue('INTERNAL_SERVER_ERROR')
  internalServerError('INTERNAL_SERVER_ERROR'),
  @JsonValue('INVALID_ACLS_FORMAT')
  invalidAclsFormat('INVALID_ACLS_FORMAT'),
  @JsonValue('INVALID_API_ORIGIN')
  invalidApiOrigin('INVALID_API_ORIGIN'),
  @JsonValue('INVALID_AUTH_TOKEN')
  invalidAuthToken('INVALID_AUTH_TOKEN'),
  @JsonValue('INVALID_BOT_FLAG')
  invalidBotFlag('INVALID_BOT_FLAG'),
  @JsonValue('INVALID_CAPTCHA')
  invalidCaptcha('INVALID_CAPTCHA'),
  @JsonValue('INVALID_CHANNEL_TYPE_FOR_CALL')
  invalidChannelTypeForCall('INVALID_CHANNEL_TYPE_FOR_CALL'),
  @JsonValue('INVALID_CHANNEL_TYPE')
  invalidChannelType('INVALID_CHANNEL_TYPE'),
  @JsonValue('INVALID_DSA_REPORT_TARGET')
  invalidDsaReportTarget('INVALID_DSA_REPORT_TARGET'),
  @JsonValue('INVALID_DSA_TICKET')
  invalidDsaTicket('INVALID_DSA_TICKET'),
  @JsonValue('INVALID_DSA_VERIFICATION_CODE')
  invalidDsaVerificationCode('INVALID_DSA_VERIFICATION_CODE'),
  @JsonValue('INVALID_FLAGS_FORMAT')
  invalidFlagsFormat('INVALID_FLAGS_FORMAT'),
  @JsonValue('INVALID_FORM_BODY')
  invalidFormBody('INVALID_FORM_BODY'),
  @JsonValue('INVALID_HANDOFF_CODE')
  invalidHandoffCode('INVALID_HANDOFF_CODE'),
  @JsonValue('INVALID_PERMISSIONS_INTEGER')
  invalidPermissionsInteger('INVALID_PERMISSIONS_INTEGER'),
  @JsonValue('INVALID_PERMISSIONS_NEGATIVE')
  invalidPermissionsNegative('INVALID_PERMISSIONS_NEGATIVE'),
  @JsonValue('INVALID_PHONE_NUMBER')
  invalidPhoneNumber('INVALID_PHONE_NUMBER'),
  @JsonValue('INVALID_PHONE_VERIFICATION_CODE')
  invalidPhoneVerificationCode('INVALID_PHONE_VERIFICATION_CODE'),
  @JsonValue('INVALID_REQUEST')
  invalidRequest('INVALID_REQUEST'),
  @JsonValue('INVALID_STREAM_KEY_FORMAT')
  invalidStreamKeyFormat('INVALID_STREAM_KEY_FORMAT'),
  @JsonValue('INVALID_STREAM_THUMBNAIL_PAYLOAD')
  invalidStreamThumbnailPayload('INVALID_STREAM_THUMBNAIL_PAYLOAD'),
  @JsonValue('INVALID_SUSPICIOUS_FLAGS_FORMAT')
  invalidSuspiciousFlagsFormat('INVALID_SUSPICIOUS_FLAGS_FORMAT'),
  @JsonValue('INVALID_SYSTEM_FLAG')
  invalidSystemFlag('INVALID_SYSTEM_FLAG'),
  @JsonValue('INVALID_TIMESTAMP')
  invalidTimestamp('INVALID_TIMESTAMP'),
  @JsonValue('INVALID_TOKEN')
  invalidToken('INVALID_TOKEN'),
  @JsonValue('INVALID_WEBAUTHN_AUTHENTICATION_COUNTER')
  invalidWebauthnAuthenticationCounter(
    'INVALID_WEBAUTHN_AUTHENTICATION_COUNTER',
  ),
  @JsonValue('INVALID_WEBAUTHN_CREDENTIAL_COUNTER')
  invalidWebauthnCredentialCounter('INVALID_WEBAUTHN_CREDENTIAL_COUNTER'),
  @JsonValue('INVALID_WEBAUTHN_CREDENTIAL')
  invalidWebauthnCredential('INVALID_WEBAUTHN_CREDENTIAL'),
  @JsonValue('INVALID_WEBAUTHN_PUBLIC_KEY_FORMAT')
  invalidWebauthnPublicKeyFormat('INVALID_WEBAUTHN_PUBLIC_KEY_FORMAT'),
  @JsonValue('INVITES_DISABLED')
  invitesDisabled('INVITES_DISABLED'),
  @JsonValue('IP_AUTHORIZATION_REQUIRED')
  ipAuthorizationRequired('IP_AUTHORIZATION_REQUIRED'),
  @JsonValue('IP_AUTHORIZATION_RESEND_COOLDOWN')
  ipAuthorizationResendCooldown('IP_AUTHORIZATION_RESEND_COOLDOWN'),
  @JsonValue('IP_AUTHORIZATION_RESEND_LIMIT_EXCEEDED')
  ipAuthorizationResendLimitExceeded('IP_AUTHORIZATION_RESEND_LIMIT_EXCEEDED'),
  @JsonValue('GLOBAL_IP_BANNED')
  globalIpBanned('GLOBAL_IP_BANNED'),
  @JsonValue('GLOBAL_IP_TEMPORARILY_BANNED')
  globalIpTemporarilyBanned('GLOBAL_IP_TEMPORARILY_BANNED'),
  @JsonValue('IP_BAN_DECLINED')
  ipBanDeclined('IP_BAN_DECLINED'),
  @JsonValue('MAX_APPLICATIONS')
  maxApplications('MAX_APPLICATIONS'),
  @JsonValue('MAX_BOOKMARKS')
  maxBookmarks('MAX_BOOKMARKS'),
  @JsonValue('MAX_CATEGORY_CHANNELS')
  maxCategoryChannels('MAX_CATEGORY_CHANNELS'),
  @JsonValue('MAX_EMOJIS')
  maxEmojis('MAX_EMOJIS'),
  @JsonValue('MAX_FAVORITE_MEMES')
  maxFavoriteMemes('MAX_FAVORITE_MEMES'),
  @JsonValue('MAX_FRIENDS')
  maxFriends('MAX_FRIENDS'),
  @JsonValue('MAX_GROUP_DM_RECIPIENTS')
  maxGroupDmRecipients('MAX_GROUP_DM_RECIPIENTS'),
  @JsonValue('MAX_GROUP_DMS')
  maxGroupDms('MAX_GROUP_DMS'),
  @JsonValue('GROUP_DM_RECIPIENTS_NOT_ADDABLE')
  groupDmRecipientsNotAddable('GROUP_DM_RECIPIENTS_NOT_ADDABLE'),
  @JsonValue('MAX_GUILD_CHANNELS')
  maxGuildChannels('MAX_GUILD_CHANNELS'),
  @JsonValue('MAX_GUILD_MEMBERS')
  maxGuildMembers('MAX_GUILD_MEMBERS'),
  @JsonValue('MAX_GUILD_ROLES')
  maxGuildRoles('MAX_GUILD_ROLES'),
  @JsonValue('MAX_GUILDS')
  maxGuilds('MAX_GUILDS'),
  @JsonValue('MAX_INVITES')
  maxInvites('MAX_INVITES'),
  @JsonValue('MAX_REACTIONS')
  maxReactions('MAX_REACTIONS'),
  @JsonValue('MAX_STICKERS')
  maxStickers('MAX_STICKERS'),
  @JsonValue('MAX_WEBHOOKS_PER_CHANNEL')
  maxWebhooksPerChannel('MAX_WEBHOOKS_PER_CHANNEL'),
  @JsonValue('MAX_WEBHOOKS_PER_GUILD')
  maxWebhooksPerGuild('MAX_WEBHOOKS_PER_GUILD'),
  @JsonValue('NCMEC_ALREADY_SUBMITTED')
  ncmecAlreadySubmitted('NCMEC_ALREADY_SUBMITTED'),
  @JsonValue('NCMEC_SUBMISSION_FAILED')
  ncmecSubmissionFailed('NCMEC_SUBMISSION_FAILED'),
  @JsonValue('MEDIA_METADATA_ERROR')
  mediaMetadataError('MEDIA_METADATA_ERROR'),
  @JsonValue('METHOD_NOT_ALLOWED')
  methodNotAllowed('METHOD_NOT_ALLOWED'),
  @JsonValue('MISSING_ACCESS')
  missingAccess('MISSING_ACCESS'),
  @JsonValue('MISSING_ACL')
  missingAcl('MISSING_ACL'),
  @JsonValue('MISSING_AUTHORIZATION')
  missingAuthorization('MISSING_AUTHORIZATION'),
  @JsonValue('MISSING_OAUTH_SCOPE')
  missingOauthScope('MISSING_OAUTH_SCOPE'),
  @JsonValue('MISSING_PERMISSIONS')
  missingPermissions('MISSING_PERMISSIONS'),
  @JsonValue('NO_ACTIVE_CALL')
  noActiveCall('NO_ACTIVE_CALL'),
  @JsonValue('NO_ACTIVE_SUBSCRIPTION')
  noActiveSubscription('NO_ACTIVE_SUBSCRIPTION'),
  @JsonValue('NOT_FOUND')
  notFound('NOT_FOUND'),
  @JsonValue('NOT_IMPLEMENTED')
  notImplemented('NOT_IMPLEMENTED'),
  @JsonValue('NO_PASSKEYS_REGISTERED')
  noPasskeysRegistered('NO_PASSKEYS_REGISTERED'),
  @JsonValue('NO_PENDING_DELETION')
  noPendingDeletion('NO_PENDING_DELETION'),
  @JsonValue('NO_USERS_WITH_FLUXERTAG_EXIST')
  noUsersWithFluxertagExist('NO_USERS_WITH_FLUXERTAG_EXIST'),
  @JsonValue('NOT_A_BOT_APPLICATION')
  notABotApplication('NOT_A_BOT_APPLICATION'),
  @JsonValue('NOT_FRIENDS_WITH_USER')
  notFriendsWithUser('NOT_FRIENDS_WITH_USER'),
  @JsonValue('NSFW_CONTENT_AGE_RESTRICTED')
  nsfwContentAgeRestricted('NSFW_CONTENT_AGE_RESTRICTED'),
  @JsonValue('PASSKEY_AUTHENTICATION_FAILED')
  passkeyAuthenticationFailed('PASSKEY_AUTHENTICATION_FAILED'),
  @JsonValue('PHONE_ADD_NOT_ELIGIBLE')
  phoneAddNotEligible('PHONE_ADD_NOT_ELIGIBLE'),
  @JsonValue('PHONE_ALREADY_USED')
  phoneAlreadyUsed('PHONE_ALREADY_USED'),
  @JsonValue('PHONE_COUNTRY_NOT_SUPPORTED')
  phoneCountryNotSupported('PHONE_COUNTRY_NOT_SUPPORTED'),
  @JsonValue('PHONE_GATE_ESCAPE_UNAVAILABLE')
  phoneGateEscapeUnavailable('PHONE_GATE_ESCAPE_UNAVAILABLE'),
  @JsonValue('PHONE_INBOUND_VERIFICATION_REQUIRED')
  phoneInboundVerificationRequired('PHONE_INBOUND_VERIFICATION_REQUIRED'),
  @JsonValue('PHONE_LOOKUP_UNAVAILABLE')
  phoneLookupUnavailable('PHONE_LOOKUP_UNAVAILABLE'),
  @JsonValue('PHONE_NUMBER_NOT_IN_SERVICE')
  phoneNumberNotInService('PHONE_NUMBER_NOT_IN_SERVICE'),
  @JsonValue('PHONE_NUMBER_NOT_MOBILE')
  phoneNumberNotMobile('PHONE_NUMBER_NOT_MOBILE'),
  @JsonValue('PHONE_RATE_LIMIT_EXCEEDED')
  phoneRateLimitExceeded('PHONE_RATE_LIMIT_EXCEEDED'),
  @JsonValue('PHONE_VERIFICATION_NEEDS_REVIEW')
  phoneVerificationNeedsReview('PHONE_VERIFICATION_NEEDS_REVIEW'),
  @JsonValue('PHONE_VERIFICATION_REQUIRED')
  phoneVerificationRequired('PHONE_VERIFICATION_REQUIRED'),
  @JsonValue('PREMIUM_PURCHASE_BLOCKED')
  premiumPurchaseBlocked('PREMIUM_PURCHASE_BLOCKED'),
  @JsonValue('PREVIEW_MUST_BE_JPEG')
  previewMustBeJpeg('PREVIEW_MUST_BE_JPEG'),
  @JsonValue('PROCESSING_FAILED')
  processingFailed('PROCESSING_FAILED'),
  @JsonValue('RATE_LIMITED')
  rateLimited('RATE_LIMITED'),
  @JsonValue('REPORT_ALREADY_RESOLVED')
  reportAlreadyResolved('REPORT_ALREADY_RESOLVED'),
  @JsonValue('REPORT_BANNED')
  reportBanned('REPORT_BANNED'),
  @JsonValue('RESPONSE_VALIDATION_ERROR')
  responseValidationError('RESPONSE_VALIDATION_ERROR'),
  @JsonValue('RESOURCE_LOCKED')
  resourceLocked('RESOURCE_LOCKED'),
  @JsonValue('SERVICE_UNAVAILABLE')
  serviceUnavailable('SERVICE_UNAVAILABLE'),
  @JsonValue('SESSION_TOKEN_MISMATCH')
  sessionTokenMismatch('SESSION_TOKEN_MISMATCH'),
  @JsonValue('SINGLE_COMMUNITY_CANNOT_CREATE_GUILDS')
  singleCommunityCannotCreateGuilds('SINGLE_COMMUNITY_CANNOT_CREATE_GUILDS'),
  @JsonValue('SINGLE_COMMUNITY_CANNOT_DELETE')
  singleCommunityCannotDelete('SINGLE_COMMUNITY_CANNOT_DELETE'),
  @JsonValue('SINGLE_COMMUNITY_CANNOT_LEAVE')
  singleCommunityCannotLeave('SINGLE_COMMUNITY_CANNOT_LEAVE'),
  @JsonValue('INSTANCE_POLICY_TRANSITION_NOT_ALLOWED')
  instancePolicyTransitionNotAllowed('INSTANCE_POLICY_TRANSITION_NOT_ALLOWED'),
  @JsonValue('SLOWMODE_RATE_LIMITED')
  slowmodeRateLimited('SLOWMODE_RATE_LIMITED'),
  @JsonValue('SMS_VERIFICATION_UNAVAILABLE')
  smsVerificationUnavailable('SMS_VERIFICATION_UNAVAILABLE'),
  @JsonValue('SSO_REQUIRED')
  ssoRequired('SSO_REQUIRED'),
  @JsonValue('STREAM_KEY_CHANNEL_MISMATCH')
  streamKeyChannelMismatch('STREAM_KEY_CHANNEL_MISMATCH'),
  @JsonValue('STREAM_KEY_SCOPE_MISMATCH')
  streamKeyScopeMismatch('STREAM_KEY_SCOPE_MISMATCH'),
  @JsonValue('STRIPE_ERROR')
  stripeError('STRIPE_ERROR'),
  @JsonValue('STRIPE_GIFT_REDEMPTION_IN_PROGRESS')
  stripeGiftRedemptionInProgress('STRIPE_GIFT_REDEMPTION_IN_PROGRESS'),
  @JsonValue('STRIPE_INVALID_PRODUCT')
  stripeInvalidProduct('STRIPE_INVALID_PRODUCT'),
  @JsonValue('STRIPE_INVALID_PRODUCT_CONFIGURATION')
  stripeInvalidProductConfiguration('STRIPE_INVALID_PRODUCT_CONFIGURATION'),
  @JsonValue('STRIPE_NO_ACTIVE_SUBSCRIPTION')
  stripeNoActiveSubscription('STRIPE_NO_ACTIVE_SUBSCRIPTION'),
  @JsonValue('STRIPE_NO_PURCHASE_HISTORY')
  stripeNoPurchaseHistory('STRIPE_NO_PURCHASE_HISTORY'),
  @JsonValue('STRIPE_REFUND_OUTSIDE_WINDOW')
  stripeRefundOutsideWindow('STRIPE_REFUND_OUTSIDE_WINDOW'),
  @JsonValue('STRIPE_REFUND_COOLDOWN_ACTIVE')
  stripeRefundCooldownActive('STRIPE_REFUND_COOLDOWN_ACTIVE'),
  @JsonValue('STRIPE_NO_SUBSCRIPTION')
  stripeNoSubscription('STRIPE_NO_SUBSCRIPTION'),
  @JsonValue('STRIPE_PAYMENT_NOT_AVAILABLE')
  stripePaymentNotAvailable('STRIPE_PAYMENT_NOT_AVAILABLE'),
  @JsonValue('STRIPE_SUBSCRIPTION_ALREADY_CANCELING')
  stripeSubscriptionAlreadyCanceling('STRIPE_SUBSCRIPTION_ALREADY_CANCELING'),
  @JsonValue('STRIPE_SUBSCRIPTION_NOT_CANCELING')
  stripeSubscriptionNotCanceling('STRIPE_SUBSCRIPTION_NOT_CANCELING'),
  @JsonValue('STRIPE_WEBHOOK_NOT_AVAILABLE')
  stripeWebhookNotAvailable('STRIPE_WEBHOOK_NOT_AVAILABLE'),
  @JsonValue('STRIPE_WEBHOOK_SIGNATURE_INVALID')
  stripeWebhookSignatureInvalid('STRIPE_WEBHOOK_SIGNATURE_INVALID'),
  @JsonValue('STRIPE_WEBHOOK_SIGNATURE_MISSING')
  stripeWebhookSignatureMissing('STRIPE_WEBHOOK_SIGNATURE_MISSING'),
  @JsonValue('DIRECT_MESSAGES_DISABLED')
  directMessagesDisabled('DIRECT_MESSAGES_DISABLED'),
  @JsonValue('DONATION_AMOUNT_INVALID')
  donationAmountInvalid('DONATION_AMOUNT_INVALID'),
  @JsonValue('DONATION_MAGIC_LINK_EXPIRED')
  donationMagicLinkExpired('DONATION_MAGIC_LINK_EXPIRED'),
  @JsonValue('DONATION_MAGIC_LINK_INVALID')
  donationMagicLinkInvalid('DONATION_MAGIC_LINK_INVALID'),
  @JsonValue('DONATION_MAGIC_LINK_USED')
  donationMagicLinkUsed('DONATION_MAGIC_LINK_USED'),
  @JsonValue('SUDO_MODE_REQUIRED')
  sudoModeRequired('SUDO_MODE_REQUIRED'),
  @JsonValue('TAG_ALREADY_TAKEN')
  tagAlreadyTaken('TAG_ALREADY_TAKEN'),
  @JsonValue('TEMPORARY_INVITE_REQUIRES_PRESENCE')
  temporaryInviteRequiresPresence('TEMPORARY_INVITE_REQUIRES_PRESENCE'),
  @JsonValue('TEST_HARNESS_DISABLED')
  testHarnessDisabled('TEST_HARNESS_DISABLED'),
  @JsonValue('TEST_HARNESS_FORBIDDEN')
  testHarnessForbidden('TEST_HARNESS_FORBIDDEN'),
  @JsonValue('TWO_FA_NOT_ENABLED')
  twoFaNotEnabled('TWO_FA_NOT_ENABLED'),
  @JsonValue('TWO_FACTOR_REQUIRED')
  twoFactorRequired('TWO_FACTOR_REQUIRED'),
  @JsonValue('UNAUTHORIZED')
  unauthorized('UNAUTHORIZED'),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_ACCEPT_FRIEND_REQUESTS')
  unclaimedAccountCannotAcceptFriendRequests(
    'UNCLAIMED_ACCOUNT_CANNOT_ACCEPT_FRIEND_REQUESTS',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_ADD_REACTIONS')
  unclaimedAccountCannotAddReactions('UNCLAIMED_ACCOUNT_CANNOT_ADD_REACTIONS'),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_CREATE_APPLICATIONS')
  unclaimedAccountCannotCreateApplications(
    'UNCLAIMED_ACCOUNT_CANNOT_CREATE_APPLICATIONS',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_CREATE_GUILDS')
  unclaimedAccountCannotCreateGuilds('UNCLAIMED_ACCOUNT_CANNOT_CREATE_GUILDS'),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_JOIN_GROUP_DMS')
  unclaimedAccountCannotJoinGroupDms('UNCLAIMED_ACCOUNT_CANNOT_JOIN_GROUP_DMS'),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_JOIN_ONE_ON_ONE_VOICE_CALLS')
  unclaimedAccountCannotJoinOneOnOneVoiceCalls(
    'UNCLAIMED_ACCOUNT_CANNOT_JOIN_ONE_ON_ONE_VOICE_CALLS',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_JOIN_VOICE_CHANNELS')
  unclaimedAccountCannotJoinVoiceChannels(
    'UNCLAIMED_ACCOUNT_CANNOT_JOIN_VOICE_CHANNELS',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_MAKE_PURCHASES')
  unclaimedAccountCannotMakePurchases(
    'UNCLAIMED_ACCOUNT_CANNOT_MAKE_PURCHASES',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_SEND_DIRECT_MESSAGES')
  unclaimedAccountCannotSendDirectMessages(
    'UNCLAIMED_ACCOUNT_CANNOT_SEND_DIRECT_MESSAGES',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_SEND_FRIEND_REQUESTS')
  unclaimedAccountCannotSendFriendRequests(
    'UNCLAIMED_ACCOUNT_CANNOT_SEND_FRIEND_REQUESTS',
  ),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_SEND_MESSAGES')
  unclaimedAccountCannotSendMessages('UNCLAIMED_ACCOUNT_CANNOT_SEND_MESSAGES'),
  @JsonValue('UNCLAIMED_ACCOUNT_CANNOT_SUBMIT_REPORTS')
  unclaimedAccountCannotSubmitReports(
    'UNCLAIMED_ACCOUNT_CANNOT_SUBMIT_REPORTS',
  ),
  @JsonValue('UNKNOWN_CHANNEL')
  unknownChannel('UNKNOWN_CHANNEL'),
  @JsonValue('UNKNOWN_EMOJI')
  unknownEmoji('UNKNOWN_EMOJI'),
  @JsonValue('UNKNOWN_FAVORITE_MEME')
  unknownFavoriteMeme('UNKNOWN_FAVORITE_MEME'),
  @JsonValue('UNKNOWN_GIFT_CODE')
  unknownGiftCode('UNKNOWN_GIFT_CODE'),
  @JsonValue('UNKNOWN_GUILD')
  unknownGuild('UNKNOWN_GUILD'),
  @JsonValue('UNKNOWN_HARVEST')
  unknownHarvest('UNKNOWN_HARVEST'),
  @JsonValue('UNKNOWN_INVITE')
  unknownInvite('UNKNOWN_INVITE'),
  @JsonValue('UNKNOWN_MEMBER')
  unknownMember('UNKNOWN_MEMBER'),
  @JsonValue('UNKNOWN_MESSAGE')
  unknownMessage('UNKNOWN_MESSAGE'),
  @JsonValue('UNKNOWN_REPORT')
  unknownReport('UNKNOWN_REPORT'),
  @JsonValue('UNKNOWN_ROLE')
  unknownRole('UNKNOWN_ROLE'),
  @JsonValue('UNKNOWN_STICKER')
  unknownSticker('UNKNOWN_STICKER'),
  @JsonValue('UNKNOWN_SUSPICIOUS_FLAG')
  unknownSuspiciousFlag('UNKNOWN_SUSPICIOUS_FLAG'),
  @JsonValue('UNKNOWN_USER_FLAG')
  unknownUserFlag('UNKNOWN_USER_FLAG'),
  @JsonValue('UNKNOWN_USER')
  unknownUser('UNKNOWN_USER'),
  @JsonValue('UNKNOWN_VOICE_REGION')
  unknownVoiceRegion('UNKNOWN_VOICE_REGION'),
  @JsonValue('UNKNOWN_VOICE_SERVER')
  unknownVoiceServer('UNKNOWN_VOICE_SERVER'),
  @JsonValue('UNKNOWN_WEBAUTHN_CREDENTIAL')
  unknownWebauthnCredential('UNKNOWN_WEBAUTHN_CREDENTIAL'),
  @JsonValue('UNKNOWN_APPLICATION')
  unknownApplication('UNKNOWN_APPLICATION'),
  @JsonValue('UNKNOWN_WEBHOOK')
  unknownWebhook('UNKNOWN_WEBHOOK'),
  @JsonValue('USERNAME_NOT_AVAILABLE')
  usernameNotAvailable('USERNAME_NOT_AVAILABLE'),
  @JsonValue('UPDATE_FAILED')
  updateFailed('UPDATE_FAILED'),
  @JsonValue('USER_BANNED_FROM_GUILD')
  userBannedFromGuild('USER_BANNED_FROM_GUILD'),
  @JsonValue('USER_IP_BANNED_FROM_GUILD')
  userIpBannedFromGuild('USER_IP_BANNED_FROM_GUILD'),
  @JsonValue('USER_NOT_IN_VOICE')
  userNotInVoice('USER_NOT_IN_VOICE'),
  @JsonValue('USER_OWNS_GUILDS')
  userOwnsGuilds('USER_OWNS_GUILDS'),
  @JsonValue('VALIDATION_ERROR')
  validationError('VALIDATION_ERROR'),
  @JsonValue('VOICE_CHANNEL_FULL')
  voiceChannelFull('VOICE_CHANNEL_FULL'),
  @JsonValue('WEBAUTHN_CREDENTIAL_LIMIT_REACHED')
  webauthnCredentialLimitReached('WEBAUTHN_CREDENTIAL_LIMIT_REACHED'),
  @JsonValue('AGE_VERIFICATION_ALREADY_VERIFIED')
  ageVerificationAlreadyVerified('AGE_VERIFICATION_ALREADY_VERIFIED'),

  /// Default value for all unparsed values, allows backward compatibility when adding new values on the backend.
  $unknown(null);

  const ApiErrorCode(this.json);

  factory ApiErrorCode.fromJson(String json) =>
      values.firstWhere((e) => e.json == json, orElse: () => $unknown);

  final String? json;

  String toJson() => json ?? 'null';

  @override
  String toString() => json ?? super.toString();

  /// Returns all defined enum values excluding the $unknown value.
  static List<ApiErrorCode> get $valuesDefined =>
      values.where((value) => value != $unknown).toList();
}
